#define POPULATION  150
#define DELTA_DISJOINT  2.0
#define DELTA_WEIGHTS  0.4
#define DELTA_THRESHOLD  1.0
#define WEIGHT_RANGE  2.0
#define BIAS_RANGE  1.0

#define STALE_SPECIES  15

#define PERTUBCHANCE  0.90
#define CROSSOVER_CHANCE  0.75

#define LINK_MUTATION_CHANCE  2.0
#define NODE_MUTATION_CHANCE  0.50
#define BIAS_MUTATION_CHANCE  1.00
#define WEIGHT_MUTATION_CHANCE  1.00
#define TRANSFER_MUTATION_CHANCE  0.5
#define STEPSIZE  0.1
#define DISBALE_MUTATION_CHANCE  0.4
#define ENABLE_MUTATION_CHANCE  0.2
#define DELETE_MUTATION_CHANCE  0.0

#define MAX_NODES  10000

#define SAVEPATH  "./save/"
